const images = [       
    { id: 1, src:  'images/2C.png', card: '2',              type: 'C', selected: false },
    { id: 2, src:  'images/2D.png', card: '2',              type: 'D', selected: false },
    { id: 3, src:  'images/2H.png', card: '2',              type: 'H', selected: false },
    { id: 4, src:  'images/2S.png', card: '2',              type: 'S', selected: false },
    { id: 5, src:  'images/3C.png', card: '3',              type: 'C', selected: false },
    { id: 6, src:  'images/3D.png', card: '3',              type: 'D', selected: false },
    { id: 7, src:  'images/3H.png', card: '3',              type: 'H', selected: false },
    { id: 8, src:  'images/3S.png', card: '3',              type: 'S', selected: false },
    { id: 9, src:  'images/4C.png', card: '4',              type: 'C', selected: false },
    { id: 10, src: 'images/4D.png', card: '4',              type: 'D', selected: false },
    { id: 11, src: 'images/4H.png', card: '4',              type: 'H', selected: false },
    { id: 12, src: 'images/4S.png', card: '4',              type: 'S', selected: false },
    { id: 13, src: 'images/5C.png', card: '5',              type: 'C', selected: false },
    { id: 14, src: 'images/5D.png', card: '5',              type: 'D', selected: false },
    { id: 15, src: 'images/5H.png', card: '5',              type: 'H', selected: false },
    { id: 16, src: 'images/5S.png', card: '5',              type: 'S', selected: false },
    { id: 17, src: 'images/6C.png', card: '6',              type: 'C', selected: false },
    { id: 18, src: 'images/6D.png', card: '6',              type: 'D', selected: false },
    { id: 19, src: 'images/6H.png', card: '6',              type: 'H', selected: false },
    { id: 20, src: 'images/6S.png', card: '6',              type: 'S', selected: false },
    { id: 21, src: 'images/7C.png', card: '7',              type: 'C', selected: false },
    { id: 22, src: 'images/7D.png', card: '7',              type: 'D', selected: false },
    { id: 23, src: 'images/7H.png', card: '7',              type: 'H', selected: false },
    { id: 24, src: 'images/7S.png', card: '7',              type: 'S', selected: false },
    { id: 25, src: 'images/8C.png', card: '8',              type: 'C', selected: false },
    { id: 26, src: 'images/8D.png', card: '8',              type: 'D', selected: false },
    { id: 27, src: 'images/8H.png', card: '8',              type: 'H', selected: false },
    { id: 28, src: 'images/8S.png', card: '8',              type: 'S', selected: false },
    { id: 29, src: 'images/9C.png', card: '9',              type: 'C', selected: false },
    { id: 30, src: 'images/9D.png', card: '9',              type: 'D', selected: false },
    { id: 31, src: 'images/9H.png', card: '9',              type: 'H', selected: false },
    { id: 32, src: 'images/9S.png', card: '9',              type: 'S', selected: false },
    { id: 33, src: 'images/10C.png', card: '10',            type: 'C', selected: false },
    { id: 34, src: 'images/10D.png', card: '10',            type: 'D', selected: false },
    { id: 35, src: 'images/10H.png', card: '10',            type: 'H', selected: false },
    { id: 36, src: 'images/10S.png', card: '10',            type: 'S', selected: false },
    { id: 37, src: 'images/AC.png', card: 'A',              type: 'C', selected: false },
    { id: 38, src: 'images/AD.png', card: 'A',              type: 'D', selected: false },
    { id: 39, src: 'images/AH.png', card: 'A',              type: 'H', selected: false },
    { id: 40, src: 'images/AS.png', card: 'A',              type: 'S', selected: false },
    { id: 41, src: 'images/JC.png', card: 'J',              type: 'C', selected: false },
    { id: 42, src: 'images/JD.png', card: 'J',              type: 'D', selected: false },
    { id: 43, src: 'images/JH.png', card: 'J',              type: 'H', selected: false },
    { id: 44, src: 'images/JS.png', card: 'J',              type: 'S', selected: false },
    { id: 45, src: 'images/KC.png', card: 'K',              type: 'C', selected: false },
    { id: 46, src: 'images/KD.png', card: 'K',              type: 'D', selected: false },
    { id: 47, src: 'images/KH.png', card: 'K',              type: 'H', selected: false },
    { id: 48, src: 'images/KS.png', card: 'K',              type: 'S', selected: false },
    { id: 49, src: 'images/QC.png', card: 'Q',              type: 'C', selected: false },
    { id: 50, src: 'images/QD.png', card: 'Q',              type: 'D', selected: false },
    { id: 51, src: 'images/QH.png', card: 'Q',              type: 'H', selected: false },
    { id: 52, src: 'images/QS.png', card: 'Q',              type: 'S', selected: false },
  ];

  
export default images;